# Permalinks
permalink:        pretty

# Setup
title:            C'est la C...++
tagline:          'Such is the coding life'
description:      'A personal website for Benjamin Espey.'
url:              http://bennyty.github.io
baseurl:          /

author:
  name:           'Benjamin Espey'
  url:            https://github.com/bennyty/

paginate:         3

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/bennyty/
